import { logger } from '@/utils/logger';
﻿/**
 * Phase 10G - Auto-injects a canonical documentation Note node into ComfyUI workflows.
 * Uses marker strings to find/replace existing auto-notes (never duplicates).
 */

export const NOTE_MARKER_START = '\u2500\u2500\u2500 fullydigital.pictures \u2500\u2500\u2500';
export const LEGACY_NOTE_MARKER_START = '\u2550\u2550\u2550 FULLYDIGITAL.PICTURES \u2550\u2550\u2550';
export const NOTE_MARKER_END = '\u2500\u2500\u2500 Generated by Workflow Architect \u2500\u2500\u2500';

// ---------- Types ----------

export interface WorkflowNoteMetadata {
  workflowName?: string;
  description?: string;
  models: ModelEntry[];
  customPacks: PackEntry[];
  generationSettings: Record<string, string | number>;
  stats: WorkflowStats;
  timestamp?: string;
}

export interface ModelEntry {
  type: string;
  filename: string;
  nodeTitle?: string;
}

export interface PackEntry {
  packName: string;
  nodeTypes: string[];
}

export interface WorkflowStats {
  totalNodes: number;
  uniqueNodeTypes: number;
  subgraphNodes: number;
  groupNodes: number;
  missingModels?: number;
}

// ---------- Main Entry Point ----------

/**
 * Injects or updates the canonical auto-generated Note node in a workflow.
 * Supports both ComfyUI UI format (nodes array) and API format (keyed by ID).
 */
export function injectWorkflowNote(
  workflow: any,
  metadata: WorkflowNoteMetadata,
): any {
  const noteText = buildNoteContent(metadata);

  if (isUIFormat(workflow)) {
    return injectNoteUIFormat(workflow, noteText);
  }
  return injectNoteAPIFormat(workflow, noteText);
}

// ---------- Format Detection ----------

function isUIFormat(workflow: any): boolean {
  return Array.isArray(workflow?.nodes);
}

// ---------- Note Content Builder ----------

export function buildNoteContent(metadata: WorkflowNoteMetadata): string {
  const lines: string[] = [];
  const ts = metadata.timestamp || formatExportTimestamp();
  const settings = metadata.generationSettings || {};
  const models = dedupeModels(metadata.models || []);
  const packs = (metadata.customPacks || []).filter((pack) => {
    const name = pack.packName.toLowerCase();
    return name !== 'comfyui core'
      && name !== 'core / unknown'
      && name !== 'unknown';
  });

  lines.push(NOTE_MARKER_START);
  lines.push('Workflow by Hleb Likhodievski');
  lines.push(`Exported: ${ts}`);
  lines.push('');
  lines.push(metadata.workflowName || 'Untitled Workflow');
  lines.push('');

  lines.push('WHAT IT DOES');
  const description = (metadata.description || '').trim();
  if (description) {
    // The description from generateWorkflowDescription already has structural
    // newlines (pipeline line, "How it works" numbered list, "Why this works"
    // bullets). formatBlock preserves those instead of collapsing into one
    // wordWrap'd paragraph.
    const blockLines = formatBlock(description, {
      indent: '  ',
      maxWidth: 72,
      skipTitle: metadata.workflowName,
    });
    for (const line of blockLines) lines.push(line);
  } else {
    lines.push('  This workflow generates images in ComfyUI using the configured models and settings.');
  }
  lines.push('');

  lines.push('HOW TO USE');
  buildHowToUse(settings).forEach((step, index) => {
    lines.push(`  ${index + 1}. ${step}`);
  });
  lines.push('');

  if (models.length > 0) {
    lines.push('MODELS USED');
    for (const entry of models) {
      lines.push(`  • ${humanizeModelName(entry.filename)} — ${humanizeCategory(entry.type)}`);
      lines.push(`    File: ${entry.filename}`);
    }
    lines.push('');
  }

  if (packs.length > 0) {
    lines.push('CUSTOM NODE PACKS');
    for (const pack of packs) {
      lines.push(`  • ${pack.packName} — ${pack.nodeTypes.length} node${pack.nodeTypes.length === 1 ? '' : 's'} used`);
    }
    lines.push('');
  }

  if (Object.keys(settings).length > 0) {
    lines.push('GENERATION SETTINGS');

    const orderedKeys = [
      'Resolution',
      'Seed',
      'Steps',
      'CFG',
      'Sampler',
      'Scheduler',
      'Denoise',
      'Batch Size',
      'Positive Prompt',
      'Negative Prompt',
    ];

    const used = new Set<string>();
    for (const key of orderedKeys) {
      if (settings[key] === undefined) continue;
      let value = settings[key];
      if (key === 'Positive Prompt' || key === 'Negative Prompt') {
        const text = String(value);
        value = text.length > 120 ? `${text.slice(0, 117)}...` : text;
      }
      lines.push(`  ${key}: ${value}`);
      used.add(key);
    }

    for (const key of Object.keys(settings)) {
      if (used.has(key)) continue;
      lines.push(`  ${key}: ${settings[key]}`);
    }

    lines.push('');
  }

  lines.push('STATS');
  lines.push(`  Nodes:        ${metadata.stats.totalNodes}  (${metadata.stats.uniqueNodeTypes} unique types)`);
  lines.push(`  Models:       ${models.length}`);
  lines.push(`  Custom packs: ${packs.length}`);
  if (metadata.stats.subgraphNodes > 0) {
    lines.push(`  Subgraphs:    ${metadata.stats.subgraphNodes}`);
  }
  if (metadata.stats.groupNodes > 0) {
    lines.push(`  Groups:       ${metadata.stats.groupNodes}`);
  }
  if (metadata.stats.missingModels !== undefined && metadata.stats.missingModels > 0) {
    lines.push(`  Missing:      ${metadata.stats.missingModels} model${metadata.stats.missingModels === 1 ? '' : 's'}`);
  }
  lines.push('');

  lines.push(NOTE_MARKER_END);
  return lines.join('\n');
}

// ---------- UI Format Injection ----------

function injectNoteUIFormat(workflow: any, noteText: string): any {
  const nodes: any[] = Array.isArray(workflow.nodes) ? workflow.nodes : [];

  const existingIdx = nodes.findIndex(
    (n: any) =>
      n?.type === 'Note'
      && typeof n?.widgets_values?.[0] === 'string'
      && (
        n.widgets_values[0].includes(NOTE_MARKER_START)
        || n.widgets_values[0].includes(LEGACY_NOTE_MARKER_START)
      ),
  );

  if (existingIdx !== -1) {
    const lineCount = noteText.split('\n').length;
    nodes[existingIdx].widgets_values = [noteText];
    nodes[existingIdx].size = [420, Math.max(220, lineCount * 18 + 40)];
    nodes[existingIdx].title = 'Workflow Info (Auto-Generated)';
    return workflow;
  }

  const newId = getNextNodeId(nodes);
  const position = calculateNotePosition(nodes);
  const lineCount = noteText.split('\n').length;

  const noteNode = {
    id: newId,
    type: 'Note',
    pos: position,
    size: [420, Math.max(220, lineCount * 18 + 40)],
    flags: {},
    order: 0,
    mode: 0,
    properties: { text: '' },
    title: 'Workflow Info (Auto-Generated)',
    widgets_values: [noteText],
    color: '#2a363b',
    bgcolor: '#3f4f54',
  };

  nodes.unshift(noteNode);
  workflow.last_node_id = Math.max(workflow.last_node_id || 0, newId);
  return workflow;
}

// ---------- API Format Injection ----------

function injectNoteAPIFormat(workflow: any, noteText: string): any {
  void noteText;
  // Note nodes are frontend-only (LiteGraph) and do not exist in ComfyUI backend.
  // Never inject into API format to avoid "missing_node_type" execution errors.
  logger.debug('[NoteInjector] Skipping API format note injection (UI-only node type)');
  return workflow;
}

// ---------- Position Calculation ----------

/**
 * Places the note node to the left of the leftmost node in the graph,
 * vertically centered among all nodes.
 */
function calculateNotePosition(nodes: any[]): [number, number] {
  if (nodes.length === 0) return [0, 0];

  let minX = Number.POSITIVE_INFINITY;
  let minY = Number.POSITIVE_INFINITY;
  let maxY = Number.NEGATIVE_INFINITY;

  for (const node of nodes) {
    const [x, y] = Array.isArray(node?.pos) ? node.pos : [0, 0];
    const h = Array.isArray(node?.size) ? Number(node.size[1] || 100) : 100;
    if (x < minX) minX = x;
    if (y < minY) minY = y;
    if (y + h > maxY) maxY = y + h;
  }

  const centerY = (minY + maxY) / 2 - 100;
  return [minX - 470, centerY];
}

// ---------- Helpers ----------

function getNextNodeId(nodes: any[]): number {
  const maxId = Math.max(0, ...nodes.map((n: any) => Number(n?.id || 0)));
  return maxId + 1;
}

function dedupeModels(models: ModelEntry[]): ModelEntry[] {
  const seen = new Set<string>();
  const result: ModelEntry[] = [];
  for (const model of models) {
    const key = `${String(model.type || '').toLowerCase()}::${String(model.filename || '').toLowerCase()}`;
    if (!model.filename || seen.has(key)) continue;
    seen.add(key);
    result.push(model);
  }
  return result;
}

function humanizeModelName(filename: string): string {
  let name = filename.replace(/\\/g, '/').split('/').pop() || filename;
  name = name.replace(/\.(safetensors|ckpt|pt|pth|bin|onnx|gguf)$/i, '');
  name = name.replace(/[_-]+/g, ' ').trim();
  if (!name) return filename;
  return name
    .split(/\s+/)
    .map((token) => {
      if (/^\d+x$/i.test(token)) return token.toLowerCase();
      if (/^sdxl$/i.test(token)) return 'SDXL';
      if (/^sd$/i.test(token)) return 'SD';
      if (/^vae$/i.test(token)) return 'VAE';
      if (/^lora$/i.test(token)) return 'LoRA';
      if (/^[A-Z0-9]{2,}$/.test(token)) return token;
      return token.charAt(0).toUpperCase() + token.slice(1);
    })
    .join(' ');
}

function humanizeCategory(category: string): string {
  const map: Record<string, string> = {
    checkpoints: 'main generation model',
    checkpoint: 'main generation model',
    loras: 'style/concept adapter',
    lora: 'style/concept adapter',
    vae: 'image encoder/decoder',
    controlnet: 'structural control model',
    clip: 'text encoder',
    clip_vision: 'image understanding model',
    upscale_models: 'upscaler for detail enhancement',
    upscale: 'upscaler for detail enhancement',
    embeddings: 'textual inversion embedding',
    ipadapter: 'image prompt adapter',
    hypernetworks: 'hypernetwork modifier',
    style_models: 'style transfer model',
    diffusion_models: 'diffusion model',
    unet: 'diffusion backbone',
    other: 'model asset',
  };
  return map[category.toLowerCase()] || category;
}

function buildHowToUse(settings: Record<string, string | number>): string[] {
  const steps: string[] = [
    'Set your prompt in "Positive Prompt" to describe the desired result',
    'Adjust generation settings (resolution, steps, CFG, sampler) if needed',
    'Click "Queue Prompt" in ComfyUI to run the workflow',
    'Review the output in preview/save nodes',
  ];

  if (typeof settings['Negative Prompt'] === 'string') {
    steps.splice(1, 0, 'Set "Negative Prompt" to exclude artifacts or unwanted elements');
  }

  return steps;
}

function formatExportTimestamp(date = new Date()): string {
  const y = date.getFullYear();
  const m = String(date.getMonth() + 1).padStart(2, '0');
  const d = String(date.getDate()).padStart(2, '0');
  const hh = String(date.getHours()).padStart(2, '0');
  const mm = String(date.getMinutes()).padStart(2, '0');
  return `${y}-${m}-${d} ${hh}:${mm}`;
}

/**
 * Format a structural text block for the auto-Note inside ComfyUI:
 *   - Preserves existing newlines so numbered lists / bullet lines stay on
 *     their own line instead of being reflown into one paragraph.
 *   - Word-wraps each individual line at maxWidth, propagating its leading
 *     indent on the continuation.
 *   - Trims trailing blank runs and collapses 3+ blank lines to 2.
 *   - Strips a single leading line if it duplicates the workflow title
 *     (avoids "Title \n Title \n description..." after the manual+auto
 *     description merge in buildFinalDescription).
 */
function formatBlock(
  text: string,
  options: { indent: string; maxWidth: number; skipTitle?: string },
): string[] {
  const { indent, maxWidth, skipTitle } = options;
  const out: string[] = [];
  const rawLines = text.replace(/\r\n/g, '\n').split('\n');

  let consumedSkipTitle = false;
  for (let rawLine of rawLines) {
    // Drop a leading exact-title duplicate ("AI modified workflow" appearing
    // both as workflow_name AND as the first line of the description).
    if (
      !consumedSkipTitle
      && skipTitle
      && rawLine.trim().toLowerCase() === skipTitle.trim().toLowerCase()
    ) {
      consumedSkipTitle = true;
      continue;
    }

    if (rawLine.trim() === '') {
      // Preserve a single blank line; collapse runs of blanks.
      if (out.length > 0 && out[out.length - 1].trim() !== '') {
        out.push('');
      }
      continue;
    }

    // Detect the leading whitespace inside the line so wrap continuations
    // line up with the bullet / number.
    const leadMatch = rawLine.match(/^(\s*)/);
    const innerLead = leadMatch ? leadMatch[1] : '';

    // Bullet normalisation: render "+" bullets as "•" for consistency with
    // the MODELS / CUSTOM NODE PACKS sections.
    rawLine = rawLine.replace(/^(\s*)\+\s+/, '$1• ');

    // Word-wrap respecting maxWidth, but treat the FIRST wrapped chunk as
    // the line itself and subsequent chunks as continuations with the
    // inner indent so a numbered step's continuation reads cleanly.
    const wrapped = wrapKeepingIndent(rawLine, maxWidth, innerLead);
    for (const piece of wrapped) {
      out.push(`${indent}${piece}`);
    }
  }

  // Drop trailing blank lines.
  while (out.length > 0 && out[out.length - 1].trim() === '') out.pop();
  return out;
}

function wrapKeepingIndent(line: string, maxWidth: number, innerLead: string): string[] {
  const trimmed = line.trimEnd();
  if (trimmed.length <= maxWidth) return [trimmed];

  const words = trimmed.split(/\s+/).filter(Boolean);
  const out: string[] = [];
  let current = innerLead;
  let isFirst = true;
  for (const word of words) {
    const candidate = current.length === innerLead.length
      ? `${innerLead}${word}`
      : `${current} ${word}`;
    if (candidate.length > maxWidth && current.trim().length > 0) {
      out.push(current);
      current = `${innerLead}    ${word}`; // continuation indent under list marker
      isFirst = false;
    } else {
      current = candidate;
    }
  }
  if (current.trim().length > 0) out.push(current);
  void isFirst;
  return out;
}
